disabled_rules:
  - type_name
  - type_body_length
  - variable_name
  - todo
  - trailing_whitespace
  - trailing_newline
  - function_body_length
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Vendors
  - Keyboard/StyleKit.swift

line_length: 
  - 300
  - 300