//
//  MessagesViewController.swift
//  Often (iMessage)
//
//  Created by Luc Succes on 6/16/16.
//  Copyright © 2016 Surf Inc. All rights reserved.
//

import UIKit
import Messages
import Nuke
import NukeAnimatedImagePlugin

class MessagesViewController: MSMessagesAppViewController {
    var viewModel: KeyboardViewModel?
    var textProcessor: TextProcessingManager?
    var packsVC: KeyboardBrowsePackItemViewController?

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.

        self.setupImageManager()
        let packsService = PacksService()
        self.packsVC = KeyboardBrowsePackItemViewController(viewModel: packsService, textProcessor: nil)
        view.backgroundColor = UIColor.oftDarkGrey74Color()

        if let packVC = self.packsVC {
            packVC.view.translatesAutoresizingMaskIntoConstraints = false
            self.view.addSubview(packVC.view)
            self.view.addConstraints([
                packVC.view.al_top == self.view.al_top,
                packVC.view.al_bottom == self.view.al_bottom,
                packVC.view.al_left == self.view.al_left,
                packVC.view.al_right == self.view.al_right
            ])
        }
    }

//    override func viewDidLayoutSubviews() {
//        super.viewDidLayoutSubviews()
//        if view.bounds == CGRect.zero {
//            return
//        }
//
//        if let packVC = packsVC {
//            packVC.view.frame = view.bounds
//        }
//    }

    func setupImageManager() {
        let decoder = ImageDecoderComposition(decoders: [AnimatedImageDecoder(), ImageDecoder()])
        let loader = ImageLoader(configuration: ImageLoaderConfiguration(dataLoader: ImageDataLoader(), decoder: decoder), delegate: AnimatedImageLoaderDelegate())
        let cache = AnimatedImageMemoryCache()
        ImageManager.shared = ImageManager(configuration: ImageManagerConfiguration(loader: loader, cache: cache))
    }


    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

}
